### ISSUE TITLE
compile failed, even roll back my project code

### ISSUE THREAD

**Issue by kuafu-run** [chen3feng/blade-build#954] opened 2021-08-16 13:26 UTC
**Describe the bug**
roll back my project code, still won't compile...

**To Reproduce**
1. Go to 'project'
2. Run 'blade build  -j32 ...'
3. See error

Blade(error): Blade build tool cc_inclusion_check error: Traceback (most recent call last):
File "xxx/blade-build-2.0/src/blade/builtin_tools.py", line 599, in main
exit_code = _BUILTIN_TOOLS[name](args=args, **options)
File "xxx/blade-build-2.0/src/blade/builtin_tools.py", line 117, in generate_cc_inclusion_check
ok, details = inclusion_check.check(info_file)
File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 399, in check
return checker.check()
File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 371, in check
check_file(src, full_src, is_header=False)
File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 352, in check_file
direct_hdrs, stacks = _parse_inclusion_stacks(path, self.build_dir)
File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 132, in _parse_inclusion_stacks
assert level == current_level + 1
AssertionError

**Expected behavior**
build success

**Error message**
If applicable, add an error message to help explain your problem.

**System (please complete the following information):**
 - cenetos 7.6
 - Python version: [e.g. 2.7.5]
 - Version [v2.0 , v2.0-beta2]

**Additional context**

the blade v2 is used in our prod environment， very hard to roll back， now is impossible to rollback to blade V1.

**Comment by chen3feng** [comment] 2021-08-17 06:52
duplicate of #112

**Closed** 2021-08-19 03:21 UTC
Labels: type: bug, type: duplicate
